// Mock data for dashboard UI development (replace with DB queries later)

export const mockUser = {
  id: "user_1",
  name: "John Developer",
  email: "demo@rongeka.com",
  image: null,
  isPro: true,
};

export const mockItemTypes = [
  { id: "type_snippet", name: "snippet", icon: "Code", color: "#3b82f6", isSystem: true, userId: null },
  { id: "type_prompt", name: "prompt", icon: "Sparkles", color: "#8b5cf6", isSystem: true, userId: null },
  { id: "type_command", name: "command", icon: "Terminal", color: "#f97316", isSystem: true, userId: null },
  { id: "type_note", name: "note", icon: "StickyNote", color: "#fde047", isSystem: true, userId: null },
  { id: "type_file", name: "file", icon: "File", color: "#6b7280", isSystem: true, userId: null },
  { id: "type_image", name: "image", icon: "Image", color: "#ec4899", isSystem: true, userId: null },
  { id: "type_link", name: "link", icon: "Link", color: "#10b981", isSystem: true, userId: null },
];

export const mockCollections = [
  {
    id: "col_1",
    name: "React Patterns",
    description: "Common React patterns and hooks",
    isFavorite: true,
    userId: "user_1",
    defaultTypeId: "type_snippet",
    itemCount: 12,
    typeIds: ["type_snippet", "type_note", "type_link"],
  },
  {
    id: "col_2",
    name: "AI Prompts",
    description: "Prompts for coding assistants",
    isFavorite: true,
    userId: "user_1",
    defaultTypeId: "type_prompt",
    itemCount: 8,
    typeIds: ["type_prompt", "type_note"],
  },
  {
    id: "col_3",
    name: "CLI Commands",
    description: "Useful terminal commands",
    isFavorite: false,
    userId: "user_1",
    defaultTypeId: "type_command",
    itemCount: 15,
    typeIds: ["type_command", "type_note"],
  },
  {
    id: "col_4",
    name: "Interview Prep",
    description: "Technical interview resources",
    isFavorite: false,
    userId: "user_1",
    defaultTypeId: null,
    itemCount: 23,
    typeIds: ["type_note", "type_snippet", "type_link", "type_command"],
  },
  {
    id: "col_5",
    name: "API References",
    description: "Quick links to API docs",
    isFavorite: false,
    userId: "user_1",
    defaultTypeId: "type_link",
    itemCount: 10,
    typeIds: ["type_link", "type_note"],
  },
  {
    id: "col_6",
    name: "TypeScript Utils",
    description: "Type utilities and helpers",
    isFavorite: false,
    userId: "user_1",
    defaultTypeId: "type_snippet",
    itemCount: 7,
    typeIds: ["type_snippet", "type_note", "type_file"],
  },
];

export const mockItems = [
  {
    id: "item_1",
    title: "useCallback Hook Pattern",
    description: "Memoized callback to prevent unnecessary re-renders",
    contentType: "TEXT" as const,
    content: "const memoizedCallback = useCallback(\n  () => {\n    doSomething(a, b);\n  },\n  [a, b],\n);",
    language: "typescript",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    isFavorite: true,
    isPinned: true,
    lastUsedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    itemTypeId: "type_snippet",
    tags: ["react", "hooks", "performance"],
    collectionIds: ["col_1"],
  },
  {
    id: "item_2",
    title: "Code Review Prompt",
    description: "AI prompt for comprehensive code reviews",
    contentType: "TEXT" as const,
    content: "Review the following code for: 1) bugs and logic errors, 2) performance issues, 3) security vulnerabilities, 4) code style and best practices. Provide specific, actionable feedback.",
    language: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    isFavorite: true,
    isPinned: false,
    lastUsedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    itemTypeId: "type_prompt",
    tags: ["ai", "review", "quality"],
    collectionIds: ["col_2"],
  },
  {
    id: "item_3",
    title: "Git Interactive Rebase",
    description: "Rebase last n commits interactively",
    contentType: "TEXT" as const,
    content: "git rebase -i HEAD~n",
    language: "bash",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    isFavorite: false,
    isPinned: false,
    lastUsedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    itemTypeId: "type_command",
    tags: ["git", "rebase"],
    collectionIds: ["col_3", "col_4"],
  },
  {
    id: "item_4",
    title: "React Server Components",
    description: "Notes on RSC architecture and data fetching",
    contentType: "TEXT" as const,
    content: "# React Server Components\n\nRSCs run only on the server. They can directly access databases, file systems, and internal services without exposing secrets to the client.",
    language: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    isFavorite: false,
    isPinned: false,
    lastUsedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    itemTypeId: "type_note",
    tags: ["react", "nextjs", "architecture"],
    collectionIds: ["col_1"],
  },
  {
    id: "item_5",
    title: "Vercel AI SDK Docs",
    description: "Official documentation for Vercel AI SDK",
    contentType: "URL" as const,
    content: null,
    language: null,
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: "https://sdk.vercel.ai/docs",
    isFavorite: true,
    isPinned: false,
    lastUsedAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    itemTypeId: "type_link",
    tags: ["vercel", "ai", "docs"],
    collectionIds: ["col_5"],
  },
  {
    id: "item_6",
    title: "Custom useFetch Hook",
    description: "Type-safe data fetching hook with SWR",
    contentType: "TEXT" as const,
    content: "import useSWR from 'swr';\n\nexport function useFetch<T>(url: string) {\n  const { data, error, isLoading } = useSWR<T>(url);\n  return { data, error, isLoading };\n}",
    language: "typescript",
    fileUrl: null,
    fileName: null,
    fileSize: null,
    url: null,
    isFavorite: false,
    isPinned: false,
    lastUsedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    userId: "user_1",
    itemTypeId: "type_snippet",
    tags: ["react", "hooks", "swr"],
    collectionIds: ["col_1"],
  },
];

export const mockRecentItems = [mockItems[0], mockItems[1], mockItems[2]];
